apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: hello
      taskRef:
        name: echo
      params:
      - name: message
        value: "$(params.message)"

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch
      default: "master"
  tasks:
    # cloning task
    - name: clone
      taskRef:
        name: checkout
      params:
      - name: repo-url
        value: "$(params.repo-url)"
      - name: branch
        value: "$(params.branch)"

    # linting task
    - name: lint
      taskRef:
        name: echo
      params: 
      - name: message
        value: "Calling Flask8 linter..."
      runAfter:
        - clone

    # tests task
    - name: tests
      taskRef:
        name: echo
      params:
      - name: message
        value: "Running unit tests with PyUnit..."
      runAfter: 
        - lint

    # build task
    - name: build
      taskRef:
        name: echo
      params:
      - name: message
        value: "Building image for $(params.repo-url)..."
      runAfter: 
        - tests
      
      # deploy task
    - name: deploy
      taskRef:
        name: echo
      params:
      - name: message
        value: "Deploying to k8s..."
      runAfter: 
        - build