apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message you want to be echoed
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  params:
    - name: repo-url
      description: The URL of the repo to clone
      type: string
    - name: branch
      description: The branch of the cloned repo on which work
      type: string
  steps:
    - name: clone
      image: bitnami/git:latest
      command: [git]
      args: ["clone", "$(params.repo-url)", "--branch", "$(params.branch)"]