name: CI workflow

on:
  push:
    branch: ["main"]
  pull_request:
    branch: ["main"]

jobs:
  build: #names the job as "build"
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout steps
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting with flask8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app